Bump next from 12.0.7 to 14.1.0
basiqio-oss/account-verification-v3 pull request #47
Opened 2024-09-27 03:55 UTC by basiq-ash

Bumps [next](https://github.com/vercel/next.js) from 12.0.7 to 14.1.0.
- [Release notes](https://github.com/vercel/next.js/releases)
- [Changelog](https://github.com/vercel/next.js/blob/canary/release.js)
- [Commits](https://github.com/vercel/next.js/compare/v12.0.7...v14.1.0)

---
updated-dependencies:
- dependency-name: next dependency-type: direct:production ...

2024-10-01 07:46 UTC, basiq-ash commented
@basiq-jon this update will fix all of the security vulnerabilities of this project. Tested on local and verified.

2024-10-07 06:45 UTC, basiq-ash commented
Preview Test: https://account-verification-v3-ndypok0mc-basiq.vercel.app/

2024-10-09 23:06 UTC, basiq-jon requested changes

2024-10-09 23:06 UTC, basiq-jon commented on package.json
>      "react-use-form-state": "^0.13.2"
Can you just update this version rather than using a resolution to resolve the conflict?

2024-10-09 23:27 UTC, basiq-jon commented on package.json
>      "react-use-form-state": "^0.13.2"
Looks like there isn't a later version, it was last updated 4 years ago and is stuck on react 16 - probably should get rid of it at some point.

2024-10-09 23:29 UTC, basiq-jon approved these changes

2024-10-09 23:29 UTC, merged